version: "3.9"
services:
  snooze-button:
    container_name: snooze-button
    restart: unless-stopped
    privileged: true
    env_file:
      - .env
    build:
      context: ./
      dockerfile: ./Dockerfile
